on:
  push:
    branches: [main, ci-workflow]
  pull_request:
    branches: [main, ci-workflow]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests with Coverage
        run: npm run test:coverage
        continue-on-error: true

  docker:
    name: Docker Build and Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t weather-app .

      - name: Run Docker container
        run: |
          docker run -d \
            -p 3000:3000 \
            -e WEATHER_API_KEY="${{ secrets.WEATHER_API_KEY }}" \
            --name weather-app-container \
            weather-app
          
          # Poczekaj na uruchomienie kontenera
          sleep 5

      - name: Test running container
        run: |
          # Test endpointu głównego
          curl -f http://localhost:3000 || exit 1

      - name: Test endpoint with secret
        run: |
          response=$(curl -s http://localhost:3000/weather/Zakopane || echo "ERROR")
          if [[ $response == "ERROR" ]]; then
            echo "Błąd pobierania danych pogodowych"
            exit 1
          fi
          if [[ $response == *"tired"* ]]; then
            echo "Aplikacja jest zmęczona, szefie."
            exit 1
          fi
